language: java
jdk:
  - openjdk11
branches:
  only:
    - master

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.gradle"
script: "./gradlew clean build"

before_deploy: # (1)
  - zip -r travis-tutorial *
  - mkdir -p deploy
  - mv travis-tutorial.zip deploy/travis-tutorial.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo setting에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo setting에 설정된 값
    bucket: travis-tutorial-build # S3 버킷
    region: us-east-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: travis-tutorial-build # S3 버킷
    key: travis-tutorial.zip
    bundle_type: zip
    application: travis-tutorial # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: travis-tutorial-deploy-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: us-east-2
    wait-until-deployed: true
    on:
      repo: eol-g/travis-tutorial
      branch: master

notifications:
  email:
    recipients:
      - kjs3870@naver.com